%Find the intrinsic parameters of the camera.
clear; 

%Set up the camera
vid1 = imaq.VideoDevice('kinectv2imaq', 1);
preview(vid1);
%Specify the number of images to be used in the calibration
NoOfImage = 30;
%Take the photos of the checkboard
for i = 1:NoOfImage
    image_capture = imresize(fliplr(step(vid1)), [240 450]);  % take camera shot
    filename = strcat('C:\Users\Sadi\github\metr4202-lab2\calib_example\Image',int2str(i),'.png')
    imwrite(image_capture,filename)
    pause(0.333333); % wait 1/3 second
end

release(vid1);

% Define images to process
imageFileNames = {'C:\Users\Sadi\github\metr4202-lab2\calib_example\Image1.png',...
    'C:\Users\Sadi\github\metr4202-lab2\calib_example\Image2.png',...
    'C:\Users\Sadi\github\metr4202-lab2\calib_example\Image3.png',...
    'C:\Users\Sadi\github\metr4202-lab2\calib_example\Image4.png',...
    'C:\Users\Sadi\github\metr4202-lab2\calib_example\Image5.png',...
    'C:\Users\Sadi\github\metr4202-lab2\calib_example\Image6.png',...
    'C:\Users\Sadi\github\metr4202-lab2\calib_example\Image7.png',...
    'C:\Users\Sadi\github\metr4202-lab2\calib_example\Image8.png',...
    'C:\Users\Sadi\github\metr4202-lab2\calib_example\Image9.png',...
    'C:\Users\Sadi\github\metr4202-lab2\calib_example\Image10.png'...
    'C:\Users\Sadi\github\metr4202-lab2\calib_example\Image11.png',...
        'C:\Users\Sadi\github\metr4202-lab2\calib_example\Image12.png',...
    'C:\Users\Sadi\github\metr4202-lab2\calib_example\Image13.png',...
    'C:\Users\Sadi\github\metr4202-lab2\calib_example\Image14.png',...
    'C:\Users\Sadi\github\metr4202-lab2\calib_example\Image15.png',...
    'C:\Users\Sadi\github\metr4202-lab2\calib_example\Image16.png',...
    'C:\Users\Sadi\github\metr4202-lab2\calib_example\Image17.png',...
    'C:\Users\Sadi\github\metr4202-lab2\calib_example\Image18.png',...
    'C:\Users\Sadi\github\metr4202-lab2\calib_example\Image19.png',...
    'C:\Users\Sadi\github\metr4202-lab2\calib_example\Image20.png'...
    'C:\Users\Sadi\github\metr4202-lab2\calib_example\Image21.png',...
        'C:\Users\Sadi\github\metr4202-lab2\calib_example\Image22.png',...
    'C:\Users\Sadi\github\metr4202-lab2\calib_example\Image23.png',...
    'C:\Users\Sadi\github\metr4202-lab2\calib_example\Image24.png',...
    'C:\Users\Sadi\github\metr4202-lab2\calib_example\Image25.png',...
    'C:\Users\Sadi\github\metr4202-lab2\calib_example\Image26.png',...
    'C:\Users\Sadi\github\metr4202-lab2\calib_example\Image27.png',...
    'C:\Users\Sadi\github\metr4202-lab2\calib_example\Image28.png',...
    'C:\Users\Sadi\github\metr4202-lab2\calib_example\Image29.png',...
    'C:\Users\Sadi\github\metr4202-lab2\calib_example\Image30.png'...
    };

% Detect checkerboards in images
[imagePoints, boardSize, imagesUsed] = detectCheckerboardPoints(imageFileNames);
imageFileNames = imageFileNames(imagesUsed);

% Generate world coordinates of the corners of the squares
squareSize = 15;  % in units of 'mm'
worldPoints = generateCheckerboardPoints(boardSize, squareSize);

% Calibrate the camera
[cameraParams, imagesUsed, estimationErrors] = estimateCameraParameters(imagePoints, worldPoints, ...
    'EstimateSkew', false, 'EstimateTangentialDistortion', false, ...
    'NumRadialDistortionCoefficients', 2, 'WorldUnits', 'mm');

% View reprojection errors
h1=figure; showReprojectionErrors(cameraParams, 'BarGraph');

% Visualize pattern locations
h2=figure; showExtrinsics(cameraParams, 'CameraCentric');

% Display parameter estimation errors
displayErrors(estimationErrors, cameraParams);

% For example, you can use the calibration data to remove effects of lens distortion.
originalImage = imread(imageFileNames{1});
undistortedImage = undistortImage(originalImage, cameraParams);

%Save the intrinsic camera parameters
save('cal.mat', 'cameraParams', 'worldPoints');