clear; % it's always good to clear the workspace!
ImageNo = 12; % start with image 2
path = 'calib_img\palm_up_north\histogram_test\';
filename = strcat(path, 'Image', num2str(ImageNo), '.png');
a = imread(filename);
% open the initial image
imshow(a);

bbox = [55, 179, (153-65), (262-179)]; % this would be generated by the detector
pause(1);

[~, ~, hueChannel] = rgb2hsv(a); % convert to HSV

imshow(insertObjectAnnotation(hueChannel, 'rectangle', bbox, 'hand'));

pause(1);

tracker = vision.HistogramBasedTracker; % create the tracker

% initialise tracker on hue pixels from palm
initializeObject(tracker, hueChannel, bbox);

% track over image3 to imag100

for ImageNo = 12:100
    filename = strcat(path, 'Image', num2str(ImageNo), '.png');
    a = imread(filename);
    [~,~,hueChannel] = rgb2hsv(a); % convert to HSV
    bbox = step(tracker, hueChannel);
    z = insertObjectAnnotation(hueChannel, 'rectangle', bbox, 'hand');
    imshow(z);
end
